name: Run Python script every 1 min

on:
  schedule:
    - cron: '0 0 */15 * * '  # This line sets the schedule

jobs:
  build:
    runs-on: ubuntu-latest
    env :
      URL : ${{secrets.URL}}
      KEY : ${{secrets.KEY}}
    
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2  # This step checks out a copy of your repository

    - name: Set up Python environment
      uses: actions/setup-python@v2  # This step sets up a Python environment
      with:
        python-version: '3.10'  # You can specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt file

    - name: Run Python script
      run: python model_eda.py  # Replace with your script's path
      env : 
        echo URL : ${{env.URL}}
        echo KEY : ${{env.KEY}}
